force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculties__c/Faculties__c.object-meta.xml
<CustomObject>
    <label>Faculties</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculties__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subjects__c</referenceTo>
    <relationshipLabel>Faculties</relationshipLabel>
    <relationshipName>Faculties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject_Course__c/Subject_Course__c.object-meta.xml
<CustomObject>
    <label>Subject Course</label>
    <nameField>
        <displayFormat>SUBID-{0000}</displayFormat>
        <label>Subject Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subject Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Subject Courses</relationshipLabel>
    <relationshipName>Subject_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject_Course__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subjects__c</referenceTo>
    <relationshipLabel>Subject Courses</relationshipLabel>
    <relationshipName>Subject_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timetable__c/Timetable__c.object-meta.xml
<CustomObject>
    <label>Timetable</label>
    <nameField>
        <displayFormat>TID-{0000}</displayFormat>
        <label>Timetable ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timetables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetable__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Timetables</relationshipLabel>
    <relationshipName>Timetables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Faculties__c.field-meta.xml
<CustomField>
    <fullName>Faculties__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faculties</label>
    <referenceTo>Faculties__c</referenceTo>
    <relationshipLabel>Timetables</relationshipLabel>
    <relationshipName>Timetables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Subject_Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Subject_Time_Slot__c</fullName>
    <label>Subject Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9 - 11</fullName>
                <default>true</default>
                <label>9 AM - 11 AM</label>
            </value>
            <value>
                <fullName>12 - 1</fullName>
                <label>12 PM - 1 PM</label>
            </value>
            <value>
                <fullName>2 - 4</fullName>
                <label>2 PM - 4 PM</label>
            </value>
            <value>
                <fullName>4 - 6</fullName>
                <label>4 PM - 6 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TimetableTriggerHandler.cls
public class TimetableTriggerHandler {
    public void handleTimetableBeforeInsert(List<Timetable__c> timetableList) {
        Map<Id, Timetable__c> timetableWithCourseId = new Map<Id, Timetable__c>();
        Map<Id, Timetable__c> timetableWithFactultyId = new Map<Id, Timetable__c>();
        List<Date> scheduledDate = new List<Date>();
        List<String> timeSlotList = new List<String>();
        
        for (Timetable__c timetable : timetableList) {
            timetableWithCourseId.put(timetable.Course__c, timetable);
			timetableWithFactultyId.put(timetable.Faculties__c, timetable);
        	scheduledDate.add(timetable.Scheduled_Date__c);
        	timeSlotList.add(timetable.Subject_Time_Slot__c);
        }
        
        // check if faculty is already assined to this timetable
        for (Timetable__c timetable : [SELECT Id, Course__c FROM Timetable__c WHERE Course__c IN :timetableWithCourseId.keySet()
                                   		AND Scheduled_Date__c IN :scheduledDate 
                                    	AND Subject_Time_Slot__c IN :timeSlotList]) 
        {
            timetableWithCourseId.get(timetable.Course__c).addError('Timetable for this course is already set');
        }
        
        // check if faculty is been allocated to other course with same time
        for (Timetable__c timetable : [SELECT Id, Faculties__c FROM Timetable__c WHERE Faculties__c IN :timetableWithFactultyId.keySet()
                                   		AND Scheduled_Date__c IN :scheduledDate 
                                    	AND Subject_Time_Slot__c IN :timeSlotList]) 
        {
            timetableWithFactultyId.get(timetable.Faculties__c).addError('Timetable for this faculty is already set');
        }        
    }
    
    public void handleSubjectsForCourse(List<Timetable__c> timetableList) {
        List<Id> timetableWithCourseId = new List<Id>();
        List<Id> timetableWithFacultyId = new List<Id>();
        
        for (Timetable__c timetable : timetableList) {
            timetableWithCourseId.add(timetable.Course__c);
            timetableWithFacultyId.add(timetable.Faculties__c);
        }
        
        Map<Id, String> subjectWithFacultyId = new Map<Id, String>();
        for (Faculties__c faculty : [SELECT Id, Subject__c FROM Faculties__c WHERE Id IN :timetableWithFacultyId]) {
            subjectWithFacultyId.put(faculty.Id, faculty.Subject__c);
        }

        System.debug('subjectWithFacultyId : ' + subjectWithFacultyId);
        
        Map<Id, Set<Id>> subjectsWithCourseId = new Map<Id, Set<Id>>();
        for (Subject_Course__c subject : [SELECT Course__c, Subject__c FROM Subject_Course__c WHERE Course__c IN :timetableWithCourseId]) {
            if (subjectsWithCourseId.containsKey(subject.Course__c) && subjectsWithCourseId.get(subject.Course__c) != null) {
                subjectsWithCourseId.get(subject.Course__c).add(subject.Subject__c);
            } 
            else {
                subjectsWithCourseId.put(subject.Course__c, new Set<Id>{subject.Subject__c});
            }
        }
        
        System.debug('subjectsWithCourseId : ' + subjectsWithCourseId);
        
        for (Timetable__c timetable : timetableList) {
            String subjectId = subjectWithFacultyId.get(timetable.Faculties__c);
            if (!subjectsWithCourseId.containsKey(timetable.Course__c) || !subjectsWithCourseId.get(timetable.Course__c).contains(subjectId)) {
                timetable.addError('Subject is not listed in course');
            }
        }
    }
}