force-app/main/default/objects/Faculties__c/Faculties__c.object-meta.xml
<CustomObject>
    <label>Faculties</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculties__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subjects__c</referenceTo>
    <relationshipLabel>Faculties</relationshipLabel>
    <relationshipName>Faculties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timetable__c/Timetable__c.object-meta.xml
<CustomObject>
    <label>Timetable</label>
    <nameField>
        <displayFormat>TID-{0000}</displayFormat>
        <label>Timetable ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timetables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetable__c/fields/Faculties__c.field-meta.xml
<CustomField>
    <fullName>Faculties__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faculties</label>
    <referenceTo>Faculties__c</referenceTo>
    <relationshipLabel>Timetables</relationshipLabel>
    <relationshipName>Timetables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <formula>Faculties__r.Subject__r.Name</formula>
    <label>Subject Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/Subject_Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Subject_Time_Slot__c</fullName>
    <label>Subject Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9 - 11</fullName>
                <default>true</default>
                <label>9 AM - 11 AM</label>
            </value>
            <value>
                <fullName>12 - 1</fullName>
                <label>12 PM - 1 PM</label>
            </value>
            <value>
                <fullName>2 - 4</fullName>
                <label>2 PM - 4 PM</label>
            </value>
            <value>
                <fullName>4 - 6</fullName>
                <label>4 PM - 6 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TimetableController.cls
public class TimetableController {

    @AuraEnabled
    public static List<Timetable__c> getTimetableRecord(String scheduledDate, String slot, String subject) {
        try {
            if (scheduledDate == null && slot == null && subject == null) {
                return [SELECT Id, Subject_Name__c, Faculties__r.Name, Subject_Time_Slot__c, Scheduled_Date__c FROM Timetable__c];
            } else {
                String query = 'SELECT Id, Subject_Name__c, Faculties__r.Name, Subject_Time_Slot__c, Scheduled_Date__c FROM Timetable__c';
                query += ' WHERE';

                boolean flag = false;
                if (scheduledDate != null && scheduledDate.length() > 0) {
                    if (flag) {
                        query += ' AND';
                    }
                    query += ' Scheduled_Date__c = ' + scheduledDate;
                    flag = true;
                } 
                if (slot != null && slot.length() > 0) {
                    if (flag) {
                        query += ' AND';
                    }
                    query += ' Subject_Time_Slot__c = ' + '\'' + slot + '\'';
                    flag = true;
                } 
                if (subject != null && subject.length() > 0) {
                    if (flag) {
                        query += ' AND';
                    }
                    query += ' Faculties__r.Subject__c = ' + '\''+ subject + '\'';
                }

                List<Timetable__c> timetableList =  Database.query(query);
                return timetableList;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteTimetableRecord(Id timetableId) {
        try {
            List<Timetable__c> timetableList = [SELECT Id FROM Timetable__c WHERE Id = :timetableId];
            if (timetableList != null && timetableList.size() > 0) {
                delete timetableList;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}